### ISSUE TITLE
2/27 Daily Review

### ISSUE THREAD

**Issue by limleesol** [HICC-Introduction/B935382-Todo_list#4]
2/26일자 Daily Review는 개인적인 문제가 생겨 업로드 하지 못했고, 2/27 것을 늦게나마 제출합니다ㅠ

### Today

- [x] 화면 설계서 수정 및 업로드

- [x] 기능 명세서 작성

### Todo

- [ ]  순서도 작성

- [ ] 필요한 기술 익히기
