### ISSUE TITLE
2/29 Daily Review

### ISSUE THREAD

**Issue by limleesol** [HICC-Introduction/B935382-Todo_list#7]
### Today

- [x] Input, button, Select 창 만들기
- [x] input에 텍스트쓰고 button 클릭하면 리스트에 li 형식으로 텍스트 쓴것이 나오게 만들기

[리스트 추가 참고](https://popcorn16.tistory.com/126) 
[리스트 추가 참고2](https://blog.naver.com/PostView.nhn?blogId=bonobonoks&logNo=221476158594&categoryNo=1&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=1&from=search)

블로그의 코드를 참고하며
createElement, getElementById, appendChild, addEventListener 에 대해 학습하고 적용했다. 내가 이해한대로 주석을 달았다.
creTodo.innerHTML = ipTodo.value; 은 잘 이해하지 못했다.

### Todo

- [ ] select한 것에 따라서 input에 입력한게 각각 다른 곳으로 append 되게 하기

### Schedule
**3/30화**
select한 것에 따라서 input에 입력한게 각각 다른 곳으로 append 되게 하기
**3/31수** 완료 기능, 텍스트 삭제, 수정 기능
**4/1목** 할일 수정 및 이동 기능
**4/2금** css
