### ISSUE TITLE
3/31 Daily Review

### ISSUE THREAD

**Issue by limleesol** [HICC-Introduction/B935382-Todo_list#8]
### Yesterday

Daily Review 작성을 잊었습니다.

- [x] select option에 따라 다른 위치에 append 시키기 (시도)

### Today

- [x]  onchange, 함수중첩으로 인한 오류 해결

계획한 것보다 벌써 늦어지기 시작했습니다

### Todo

- [ ] append 한 것들 각각에 버튼 생성하기
- [ ] 생성한 버튼에 onchange에 따라 이동하는 select 기능 넣기
- [ ] 생성한 버튼에 remove 기능 넣기
