### ISSUE TITLE
4/1 Daily Review

### ISSUE THREAD

**Issue by limleesol** [HICC-Introduction/B935382-Todo_list#9]
###Today

- [x] 삭제 기능 구현 

- append를 select option에 따라 각각 다른 id값의 ul로 했더니 삭제하려는 li가 있는 select를 먼저 선택해야만 삭제가 가능한 문제가 발생해서 예상보다 오래걸렸습니다. 해결완료 

### Todo

- [ ] 우선순위 변경 기능

- [ ] 텍스트 수정 기능

- [ ] 완료 기능
